# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install -g @angular/cli
      - run: bash build.sh

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          name: dist
          path: ./dist/index/*

      - name: SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "index.tar"
          target: "/www/wwwroot/www.celess.cn"

      - name: Run SSH command
        uses: garygrossgarten/github-action-ssh@v0.5.0
        with:
          command: cd /www/wwwroot/www.celess.cn && bash deploy.sh
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
